all: quadrados_coloridos disco_quadrado poligono_regular

quadrados_coloridos: quadrados_coloridos.c
	gcc quadrados_coloridos.c -o quadrados -lGL -lglut
	
disco_quadrado: disco_quadrado.c
	gcc disco_quadrado.c -o disco -lGL -lglut

poligono_regular: poligono_regular.c
	gcc poligono_regular.c -o poligono -lGL -lglut -lm
